type: middleware
import: gitlab.com/evolves-fr/traefik-plugin-redirect
displayName: Regex Redirect With Status Code
summary: The RedirectRegex redirects a request using regex matching and replacement with custom status code
testData:
  redirects:
    - regex: /redirect
      replacement: /ok
      statusCode: 302
    - regex: ^/gone$
      statusCode: 410
    - regex: ^/not-found$
      statusCode: 404
