# The name of your plugin as displayed in the Traefik Pilot web UI.
displayName: Fast Redirect With Status Code

# For now, `middleware` is the only type available.
type: middleware

# The import path of your plugin.
import: github.com/epicagency/traefik-plugin-redirect

# A brief description of what your plugin is doing.
summary: Fast Redirect is a Traefik plugin to redirect a list with status code.

# Medias associated to the plugin (optional)
iconPath: icon.png
#bannerPath: banner.png

# Configuration data for your plugin.
# This is mandatory,
# and Traefik Pilot will try to execute the plugin with the data you provide as part of its startup validity tests.
testData:
  debug: false
  redirects:
    - /redirect:/ok:302
    - /gone::410
    - /not-found::404
